import { Link, createFileRoute, notFound } from '@tanstack/react-router'
import { useInView } from 'motion/react'
import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { Reveal } from '#/components/Reveal'
import { RoleCard } from '#/components/RoleCard'
import { useIsClearOfChildren } from '#/hooks/useIsClearOfChildren'
import { brandHighlights, fullName, profile, roles, siteUrl, skills } from '#/content/cv'

const description = `Work history and skills of ${fullName}, ${profile.title.toLowerCase()}.`

// Generated by scripts/generate-pdfs.mjs from the print layout of each view
const pdfs = {
  full: '/Fergus-Ruston-CV.pdf',
  summary: '/Fergus-Ruston-CV-Summary.pdf',
}

export const Route = createFileRoute('/experience/{-$view}')({
  beforeLoad: ({ params }) => {
    if (params.view !== undefined && params.view !== 'summary') throw notFound()
  },
  head: ({ params }) => {
    const isSummary = params.view === 'summary'
    const url = `${siteUrl}/experience${isSummary ? '/summary' : ''}`

    return {
      meta: [
        { title: `${isSummary ? 'Experience summary' : 'Experience'} | ${fullName}` },
        { name: 'description', content: description },
        { property: 'og:url', content: url },
      ],
      links: [{ rel: 'canonical', href: url }],
    }
  },
  component: Experience,
})

const sectionHeading = 'display text-3xl md:text-5xl print:text-xl'
const sectionGrid =
  'grid gap-x-10 gap-y-6 py-6 md:grid-cols-[15rem_minmax(0,1fr)] md:py-10 print:grid-cols-[minmax(0,1fr)_minmax(0,3fr)] print:py-4'

const viewFadeMs = 200

const button = 'block border-4 px-5 py-3 text-center font-bold transition-colors'

function BrandHighlights({
  className,
  children,
}: {
  className?: string
  children?: ReactNode
}) {
  return (
    <section className={className}>
      <h2 className="font-extrabold">Brand Highlights</h2>
      <p className={children ? 'mb-4 print:mb-2' : undefined}>{brandHighlights.join(', ')}</p>
      {children}
    </section>
  )
}

const caseStudies = roles.flatMap((role) => role.links ?? [])

function CaseStudies() {
  return (
    <>
      <h2 className="font-extrabold">Case Studies</h2>
      <ul className="mt-2 flex flex-wrap gap-3 print:mt-0 print:block">
        {caseStudies.map((link) => (
          <li key={link.href}>
            {/* Backgrounds are not printed, so in print these fall back to plain underlined links */}
            <a
              href={link.href}
              className="inline-block border-2 border-fg bg-fg px-3 py-1 text-base font-bold text-bg transition-colors hover:bg-bg hover:text-fg print:border-0 print:bg-transparent print:p-0 print:font-normal print:text-fg print:underline"
            >
              {link.subject}
            </a>
          </li>
        ))}
      </ul>
    </>
  )
}

function Experience() {
  const introRef = useRef<HTMLDivElement>(null)
  const scrollCueRef = useRef<SVGSVGElement>(null)
  const rolesRef = useRef<HTMLElement>(null)
  // Same viewport margin as Reveal, so the cue goes as the first role starts to animate in
  const rolesInView = useInView(rolesRef, { once: true, margin: '0px 0px -12% 0px' })
  const scrollCueIsClear = useIsClearOfChildren(scrollCueRef, introRef)
  const isSummary = Route.useParams().view === 'summary'
  // The view on screen lags the address by a fade-out, so the old content leaves before the new arrives
  const [shownSummary, setShownSummary] = useState(isSummary)
  const isSwitchingView = isSummary !== shownSummary
  const showScrollCue = scrollCueIsClear && !rolesInView && !isSummary
  const viewFade = `transition-opacity duration-200 motion-reduce:transition-none ${isSwitchingView ? 'opacity-0' : ''}`

  useEffect(() => {
    if (!isSwitchingView) return
    const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    const timer = setTimeout(() => setShownSummary(isSummary), reduceMotion ? 0 : viewFadeMs)
    return () => clearTimeout(timer)
  }, [isSummary, isSwitchingView])

  return (
    <main className="px-(--gutter) pb-24 print:p-0">
      <h1 className="fit pt-6 md:pt-12 print:hidden">
        <span className="display page-title block">Experience</span>
      </h1>

      <header className="hidden print:block">
        <p className="display text-4xl">{fullName}</p>
        <p className="mt-2 font-semibold">
          {profile.title}, {profile.location}. {profile.email}
        </p>
      </header>

      <div
        ref={introRef}
        className="mt-8 flex flex-col gap-6 min-[1150px]:flex-row min-[1150px]:items-start min-[1150px]:justify-between md:mt-12 print:mt-4"
      >
        {shownSummary ? (
          <div
            className={`max-w-[60ch] space-y-8 text-lg/relaxed md:text-xl/relaxed print:space-y-4 print:text-base ${viewFade}`}
          >
            <BrandHighlights>
              <CaseStudies />
            </BrandHighlights>
            <ul className="list-[square] space-y-5 pl-5 print:space-y-3">
              {roles.map((role) => (
                <li key={`${role.company}-${role.startYear}`}>
                  <p className="font-extrabold">
                    {role.title}, {role.company}
                  </p>
                  <p className="text-muted">
                    {role.dates}
                    {role.employment && `, ${role.employment}`}
                  </p>
                  {role.technologies && <p>{role.technologies.join(', ')}</p>}
                </li>
              ))}
            </ul>
          </div>
        ) : (
          <div
            className={`max-w-[60ch] space-y-4 text-lg/relaxed md:text-xl/relaxed print:space-y-2 print:text-base ${viewFade}`}
          >
            {profile.summary.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
            <BrandHighlights className="pt-4 print:pt-2" />
          </div>
        )}
        <div className="flex flex-wrap gap-3 min-[1150px]:flex-col print:hidden">
          <a
            href={isSummary ? pdfs.summary : pdfs.full}
            download
            className={`${button} border-fg bg-fg text-bg hover:bg-bg hover:text-fg`}
          >
            Download PDF
          </a>
          <Link
            to="/experience/{-$view}"
            params={{ view: isSummary ? undefined : 'summary' }}
            viewTransition={false}
            resetScroll={false}
            className={`${button} border-bg bg-bg text-fg hover:border-fg hover:bg-fg hover:text-bg`}
          >
            {/* Both labels share one grid cell so the button keeps the width of the longer one */}
            <span className="grid">
              <span className={`col-start-1 row-start-1 ${isSummary ? 'invisible' : ''}`}>
                View summary
              </span>
              <span className={`col-start-1 row-start-1 ${isSummary ? '' : 'invisible'}`}>
                View full CV
              </span>
            </span>
          </Link>
          {/* With no left or right set, a fixed element keeps its place in the column, so it centres under the buttons */}
          <svg
            ref={scrollCueRef}
            aria-hidden
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="3"
            className={`scroll-cue pointer-events-none fixed right-(--gutter) bottom-6 hidden size-10 min-[1150px]:right-auto min-[1150px]:self-center transition-opacity duration-300 md:block print:hidden ${showScrollCue ? '' : 'opacity-0'}`}
          >
            <path d="M4 8l8 8 8-8" />
          </svg>
        </div>
      </div>

      {/* Hidden rather than unmounted in summary view, so roles that have animated in stay that way */}
      <div className={`${viewFade} ${shownSummary ? 'hidden' : ''}`}>
        <section ref={rolesRef} className="mt-12 md:mt-20 print:mt-6">
          <h2 className="sr-only">Work history</h2>
          {roles.map((role) => (
            <RoleCard key={`${role.company}-${role.startYear}`} role={role} />
          ))}
        </section>

        <Reveal>
          <section className={sectionGrid}>
            <h2 className={sectionHeading}>Skills</h2>
            <dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2">
              {skills.map((group) => (
                <div key={group.name}>
                  <dt className="font-extrabold">{group.name}</dt>
                  <dd className="mt-1">{group.items.join(', ')}</dd>
                </div>
              ))}
            </dl>
          </section>
        </Reveal>
        <div className="rule" />
      </div>
    </main>
  )
}
